name: Build Jiafei Snakey Dookey

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Jiafei Snakey Dookey
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install pygbag
      run: |
        echo "Attempting to install pygbag"
        python -m pip install pygbag
        echo "Successfully installed pygbag"

    - name: Create Symbolic Link for main.py
      run: |
        echo "Creating symbolic link from snake.py to main.py"
        ln -s snake.py main.py
        echo "Symbolic link created"

    - name: Build the game
      run: |
        echo "Attempting to build the game"
        python -m pygbag --build $GITHUB_WORKSPACE
        echo "Successfully built the game and compiled to WebAssembly"

    - name: Upload to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: jiafei_snakey_dookey/web
